spring.application.name=user-service
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/turkcelldb
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT ayarları
# Gizli anahtar — token imzalamak için kullanılır, kimseyle paylaşılmaz
jwt.secret=turkcell-secret-key-2024-very-long-secret-key-for-security
# Token geçerlilik süresi — 24 saat (millisecond cinsinden)
jwt.expiration=86400000